[package]
name = "node_store_bridge"
version = "0.35.0"
edition = "2024"

[package.metadata.polylith]
interface = "node_store_bridge"

[dependencies]
node_store = { workspace = true }
schema = { workspace = true }
content = { workspace = true }
template = { workspace = true }
im = { workspace = true }
