[package]
name = "ned_cli"
version = "0.35.0"
edition = "2024"

[dependencies]
node_store = { workspace = true }
node_store_bridge = { workspace = true }
schema = { workspace = true }
content = { workspace = true }
template = { workspace = true }
site_repository = { workspace = true }
site_index = { workspace = true }
im = { workspace = true }
ned = { workspace = true }
evaluator = { workspace = true }
